[package]
name = "litertlm-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
description = "Safe Rust bindings to LiteRT-LM"
build = "build.rs"

include = [
    "src/",
    "examples/",
    "build.rs",
    "Cargo.toml",
    "README.md",
]

[dependencies]
litertlm-sys = { workspace = true }
serde_json = "1"
