//! Raw, unsafe FFI bindings to LiteRT LM's C API (`conversation.h` +
//! `engine.h`), generated by `bindgen` at build time. See the `litert-lm`
//! crate for a safe wrapper.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
